# Generated by Django 6.0.2 on 2026-02-13 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('task_type', models.CharField(choices=[('BEDROCK', 'Amazon Bedrock'), ('STEP_FUNCTION', 'AWS Step Function'), ('ECS', 'Amazon ECS'), ('CUSTOM', 'Custom Automation')], default='CUSTOM', max_length=20, verbose_name='tipo de tarefa')),
                ('provider_id', models.CharField(blank=True, help_text='ARN da Step Function, ID do ECS Cluster ou Modelo do Bedrock.', max_length=255, verbose_name='ID do provedor (ARN/ID)')),
                ('execution_status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Em Execução'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='status de execução')),
                ('input_params', models.JSONField(blank=True, default=dict, verbose_name='parâmetros de entrada')),
                ('output_results', models.JSONField(blank=True, default=dict, verbose_name='resultados da saída')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_tasks', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'tarefa de automação',
                'verbose_name_plural': 'tarefas de automação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
