# Generated by Django 6.0.2 on 2026-02-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0002_automationtask_delete_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtask',
            name='task_type',
            field=models.CharField(choices=[('BEDROCK', 'Amazon Bedrock'), ('STEP_FUNCTION', 'AWS Step Function'), ('ECS', 'Amazon ECS'), ('EKS', 'Elastic Kubernetes Service'), ('CUSTOM', 'Custom Automation')], default='CUSTOM', max_length=20, verbose_name='tipo de tarefa'),
        ),
    ]
