# Generated by Django 6.0.2 on 2026-02-20 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0003_alter_automationtask_task_type'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='associated_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_tasks', to='support.resolvecase', verbose_name='caso associado'),
        ),
    ]
