# Generated by Django 6.0.2 on 2026-02-13 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolveCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('category', models.CharField(choices=[('TECHNICAL', 'Técnico'), ('BILLING', 'Faturamento'), ('AI_REFINEMENT', 'Refinamento de IA'), ('OTHER', 'Outro')], default='TECHNICAL', max_length=20, verbose_name='categoria')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em Andamento'), ('RESOLVED', 'Resolvido'), ('CLOSED', 'Fechado')], default='OPEN', max_length=20, verbose_name='status')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='notas de resolução')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_cases', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'caso de suporte',
                'verbose_name_plural': 'casos de suporte',
                'ordering': ['-created_at'],
            },
        ),
    ]
