# Generated by Django 5.2.11 on 2026-02-20 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, help_text='Token do dispositivo para notificações push', max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS (APNS)'), ('android', 'Android (FCM)'), ('web', 'Web Push')], default='android', help_text='Plataforma do dispositivo', max_length=20)),
                ('device_id', models.CharField(blank=True, help_text='ID único do dispositivo (opcional)', max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, help_text='Nome do dispositivo (opcional)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o token está ativo para recebimento de notificações')),
                ('user', models.ForeignKey(help_text='Usuário proprietário do dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Dispositivo',
                'verbose_name_plural': 'Tokens de Dispositivo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Título da notificação', max_length=255)),
                ('body', models.TextField(help_text='Corpo/mensagem da notificação')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Dados adicionais da notificação (payload)')),
                ('template', models.CharField(blank=True, help_text='Template utilizado (se aplicável)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], db_index=True, default='pending', help_text='Status de entrega da notificação', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Data/hora de envio', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Data/hora de entrega confirmada', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro (se falhou)')),
                ('retry_count', models.IntegerField(default=0, help_text='Número de tentativas de reenvio')),
                ('fcm_message_id', models.CharField(blank=True, help_text='ID da mensagem no Firebase (se disponível)', max_length=255)),
                ('device_token', models.ForeignKey(blank=True, help_text='Token de dispositivo utilizado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='notifications.devicetoken')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário destinatário (opcional para broadcasts)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['token'], name='notificatio_token_1a2c49_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_f0e72c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['platform', 'is_active'], name='notificatio_platfor_786102_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_68c9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_a3de53_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['template', 'created_at'], name='notificatio_templat_eec3d4_idx'),
        ),
    ]
